FROM --platform=linux/amd64 ubuntu:16.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less file locate && echo 'alias locate="updatedb && locate"' >> ~/.bashrc
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake libz-dev libclang-dev llvm-3.7-dev libedit-dev

COPY . /repo
WORKDIR /repo/LLVM-compiler/build
RUN cmake ..
RUN make -j8
